-----------
--TABELAS--
-----------

SELECT * FROM ARQUIVO_DOCUMENTO; --WHERE CD_ARQUIVO_DOCUMENTO = 3591;
SELECT * FROM ARQUIVO_ATENDIMENTO; --WHERE CD_PACIENTE = 469646;
--SELECT * FROM ALL_OBJECTS ao WHERE ao.OBJECT_NAME LIKE '%CNT_ARQU_AT%';

-----------
--PADROES--
-----------

--CD_STATUS_ARQUIVO_ATENDIMENTO - 622 (finalizado)
--CD_OBJETO_SELECIONADO - 222 (padrão)

------------
--NEXTAVAL--
------------

--CD_ARQUIVO_DOCUMENTO
SELECT SEQ_ARQUIVO_DOCUMENTO.nextval FROM DUAL;

--CD_ARQUIVO_ATENDIMENTO
SELECT SEQ_ARQUIVO_ATENDIMENTO.nextval FROM DUAL;

--CD_DOCUMENTO CLINICO
SELECT SEQ_PW_DOCUMENTO_CLINICO.nextval FROM DUAL;

SELECT * FROM all_objects WHERE object_type = 'SEQUENCE' AND object_name LIKE '%ARQUIVO_DOCUMENTO%'

SELECT SEQ_ARQUIVO_DOCUMENTO.nextval FROM DUAL;

-------------
--SIMULACAO--
-------------

--CD PACIENTE
--CD_ATENDIMENTO
--CD_USUARIO
--NM_USUARIO
--NOME DO ARQUIVO COM EXENTSAO
--EXTENSAO
--CD_ARQUIVO_DOCUMENTO
--CD_DOCUMENTO_CLINICO

--**--**--**--**--**--**--**--**
--1ª ETAPA - ARQUIVO DOCUMENTO
--**--**--**--**--**--**--**--**

INSERT INTO dbamv.ARQUIVO_DOCUMENTO
SELECT SEQ_ARQUIVO_DOCUMENTO.nextval AS CD_ARQUIVO_DOCUMENTO, --NEXTVAL
(SELECT LO_ARQUIVO_DOCUMENTO FROM dbamv.ARQUIVO_DOCUMENTO WHERE CD_ARQUIVO_DOCUMENTO = 18),
--'' AS LO_ARQUIVO_DOCUMENTO, 
'PNG' AS TP_EXTENSAO, --VARIAVEL
NULL AS DS_AUTOR, 
NULL AS DS_ORIGEM, 
NULL AS DT_DOCUMENTO, 
'DEBORA INTERMEDICA.png' AS DS_NOME_ARQUIVO --VARIAVEL
FROM DUAL;

COMMIT;

--SELECT MAX(CD_ARQUIVO_DOCUMENTO) FROM dbamv.ARQUIVO_DOCUMENTO ORDER BY 1 DESC;

--**--**--**--**--**--**--**--**
--2ª ETAPA - DOCUMENTO CLINICO
--**--**--**--**--**--**--**--**

INSERT INTO PW_DOCUMENTO_CLINICO
SELECT SEQ_PW_DOCUMENTO_CLINICO.nextval AS CD_DOCUMENTO_CLINICO, --NEXTVAL
2 AS CD_TIPO_DOCUMENTO, 
NULL AS CD_DOCUMENTO_DIGITAL,
'638022' AS CD_PACIENTE, --VARIAVEL
'3988637' AS CD_ATENDIMENTO, --VARIAVEL
'HSSAMPAIO' AS CD_USUARIO, --VARIAVEL
'2008' AS CD_PRESTADOR, --VARIAVEL
'FECHADO' AS TP_STATUS,
SYSDATE AS DH_REFERENCIA,
SYSDATE AS DH_CRIACAO,
SYSDATE AS DH_FECHAMENTO,
NULL AS DH_IMPRESSO,
'IMAGEM' AS TP_EXTENSAO, --PDF_ANEXO (VERIFICAR SE VAI SER SO FOTO OU NAO)
NULL AS CD_SETOR,
222 As CD_OBJETO,
NULL AS CD_DOCUMENTO_CANCELADO,
'DEBORA INTERMEDICA.png' AS NM_DOCUMENTO, --VARIAVEL
NULL AS NM_VERSAO_DOCUMENTO,
SYSDATE AS DH_DOCUMENTO,
NULL AS CD_DOCUMENTO_CLINICO_NOVO,
NULL AS CD_DOC_CLINICO_REFERENCIA,
NULL AS CD_USUARIO_AUTORIZADOR,
NULL AS SN_INTEGRA_GREEN,
NULL AS CD_MULTI_EMPRESA,
NULL AS SN_CONFIDENCIAL,
NULL AS QT_VIAS_IMPRESSAS
FROM DUAL;

COMMIT;

--SELECT * FROM PW_DOCUMENTO_CLINICO dc ORDER BY 1 DESC;

--**--**--**--**--**--**--**--**
--3º ETAPA ARQUIVO_ATENDIMENTO
--**--**--**--**--**--**--**--**

INSERT INTO dbamv.ARQUIVO_ATENDIMENTO 
SELECT SEQ_ARQUIVO_ATENDIMENTO.nextval AS CD_ARQUIVO_ATENDIMENTO, --NEXTVAL
(SELECT MAX(CD_ARQUIVO_DOCUMENTO) FROM dbamv.ARQUIVO_DOCUMENTO) AS CD_ARQUIVO_DOCUMENTO, --NEXTAVEL DE OUTRA TABELA
'3988637' AS CD_ATENDIMENTO, --VARIAVEL
SYSDATE AS DH_CRIACAO,
'HEITOR SCALABRINI SAMPAIO' AS NM_USUARIO, --VARIAVEL
NULL AS CD_TIPO_DOCUMENTO, 
'638022' AS CD_PACIENTE,  --VARIAVEL
NULL AS CD_PW_TIPO_DOCUMENTO,
(SELECT MAX(CD_DOCUMENTO_CLINICO) FROM dbamv.PW_DOCUMENTO_CLINICO) AS CD_DOCUMENTO_CLINICO, --NEXTAVEL DE OUTRA TABELA
NULL AS DS_DESCRICAO,
661 AS CD_STATUS_ARQUIVO_ATENDIMENTO,
222 AS CD_OBJETO_SELECIONADO
FROM DUAL;

COMMIT;

--SELECT * FROM dbamv.ARQUIVO_ATENDIMENTO ORDER BY 1 DESC;

SELECT *
FROM PACIENTE 
WHERE CD_PACIENTE = 608160

SELECT * FROM dbamv.ARQUIVO_ATENDIMENTO
WHERE CD_PACIENTE IN (286821,608160)
FOR UPDATE;

SELECT * FROM dbamv.ARQUIVO_DOCUMENTO
WHERE CD_ARQUIVO_DOCUMENTO IN (18,3170,3172,3173)

SELECT *
FROM PW_DOCUMENTO_CLINICO dc
WHERE CD_PACIENTE = 608160
ORDER BY 1 DESC
